import type { Metadata } from "next";
import "./globals.css";
import { SearchBar } from "@/components/search-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="bg-white shadow-sm border-b">
          <div className="container mx-auto px-4 py-4">
            <div className="flex items-center justify-between">
              <h1 className="text-xl font-bold">Go4Movies</h1>
              <div className="flex-1 max-w-md mx-4">
                <SearchBar />
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
